version: '3.9'
services:
  postgresql:
    image: postgres:14
    container_name: vk
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    networks:
      - backend

    volumes:
      - postgresql-data:/var/lib/postgresql/data


  liquibase-migrations:
    image: liquibase/liquibase:4.18
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/vk
      - --username=postgres
      - --password=password
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    depends_on:
      - postgresql

    networks:
      - backend

volumes:
  postgresql-data:
    name: postgres-data-volume


networks:
  backend:
